### PR TITLE
feat: add sepolia support

### PR DESCRIPTION
**Pull request by Sekhmet**
## Test plan

- Make sure your Infura API has Starknet Sepolia enabled.
- Start with `NETWORK_NODE_URL=https://starknet-sepolia.infura.io/v3/API_KEY NETWORK=SN_SEPOLIA yarn dev`

### CODE REVIEW

**Comment by Sekhmet** [comment]
@bonustrack we will need separate URL to deploy it as well, similar to mainnet/goerli (testnet).

**Comment by bonustrack** [comment]
Goerli will not stay available that long, we can deprecate it on the UI and use https://testnet-api-1.snapshotx.xyz endpoint for Sepolia.

**Comment by Sekhmet** [comment]
Sounds good to me. If it looks good to you we can just merge this as is and swap network for testnet-api and I will remove goerli from UI.

**Comment by Sekhmet** [comment]
Herodotus works now. I will merge and we can start migrating testnet-api-1 to sepolia.

**Pull request merged**
