### PR TITLE
refactor: use Checkpoint ORM

### PR DESCRIPTION
**Pull request by Sekhmet**
Depends on: https://github.com/checkpoint-labs/checkpoint/pull/253
Depends on: https://github.com/checkpoint-labs/checkpoint/pull/252

### CODE REVIEW

**Comment by bonustrack** [comment]
@Sekhmet We need generate in the build script too otherwise server fail to deploy on DO
```
[2023-09-22 13:29:48] │ Running custom build command: yarn build
[2023-09-22 13:29:49] │ yarn run v1.22.19
[2023-09-22 13:29:49] │ $ tsc -p tsconfig.build.json
[2023-09-22 13:30:03] │ src/ipfs.ts(5,8): error TS2307: Cannot find module '../.checkpoint/models' or its corresponding type declarations.
[2023-09-22 13:30:03] │ src/utils.ts(8,46): error TS2307: Cannot find module '../.checkpoint/models' or its corresponding type declarations.
[2023-09-22 13:30:03] │ src/writer.ts(5,45): error TS2307: Cannot find module '../.checkpoint/models' or its corresponding type declarations.
[2023-09-22 13:30:03] │ error Command failed with exit code 2.
```

**Comment by bonustrack** [comment]
Also it seem to miss this, weird I was thinking you already added somewhere 
```
if (process.env.CA_CERT) {
  process.env.CA_CERT = process.env.CA_CERT.replace(/\\n/g, '\n');
}
```

**Comment by Sekhmet** [comment]
@bonustrack this should be handled there:
https://github.com/checkpoint-labs/checkpoint/blame/27a74fa68174d1542e9ee77993df7d71d42949c9/src/knex.ts#L57-L61

**Comment by bonustrack** [comment]
@Sekhmet You mean we should change Checkpoint to parse CA_CERT rather than doing it here?

**Comment by Sekhmet** [comment]
Ah, I see that's DO specific to convert it to multiline.

**Comment by bonustrack** [comment]
Ok deployment works but I got this error now on indexing 2nd space:
```
error: insert into "spaces" ("authenticators", "controller", "created", "id", "max_voting_period", "metadata", "min_voting_period", "proposal_count", "proposal_threshold", "strategies", "strategies_metadata", "strategies_params", "tx", "validation_strategy", "validation_strategy_params", "vote_count", "voting_delay", "voting_power_validation_strategy_strategies", "voting_power_validation_strategy_strategies_params") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) - duplicate key value violates unique constraint "spaces_pkey
```
Not sure if it's related to Postgres

**Comment by Sekhmet** [comment]
@bonustrack we don't have multiple containers using/multiple deployments using single DB?

**Comment by bonustrack** [comment]
Nope just re-verified

**Comment by bonustrack** [comment]
But 2 instances of the same deployment might be living in same time when an update happen, maybe with a sleep(20e3) before `checkpoint.reset()` it wont happen?

**Comment by Sekhmet** [comment]
We can try that.

**Comment by bonustrack** [comment]
Same error

**Comment by bonustrack** [comment]
On the original instance with MySQL it works

**Comment by bonustrack** [comment]
I can reproduce the issue locally with a different database (but still with Postgres)

**Comment by Sekhmet** [comment]
I will take a look.

**Comment by bonustrack** [comment]
This is still happening for me:
https://github.com/snapshot-labs/sx-api/issues/188

**Comment by Sekhmet** [comment]
@bonustrack this PR isn't supposed to handle this.

**Review by bonustrack — APPROVED** [review]
tACK

**Pull request merged**
